RSS_FEEDS = [
    # CNBC
    "https://www.cnbc.com/id/100003114/device/rss/rss.html",   # Top News
    "https://www.cnbc.com/id/10000664/device/rss/rss.html",    # Finance
    "https://www.cnbc.com/id/15839069/device/rss/rss.html",    # Tech
    "https://www.cnbc.com/id/10000115/device/rss/rss.html",    # US News
    "https://www.cnbc.com/id/20910258/device/rss/rss.html",    # Earnings

    # MarketWatch
    "https://www.marketwatch.com/rss/topstories",
    "https://www.marketwatch.com/rss/marketpulse",

    # Reuters
    "https://feeds.reuters.com/reuters/businessNews",
    "https://feeds.reuters.com/reuters/technologyNews",
    "https://feeds.reuters.com/reuters/healthNews",

    # Yahoo Finance
    "https://finance.yahoo.com/rss/topfinstories",
    "https://finance.yahoo.com/rss/2.0/headline?s=AAPL&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=MSFT&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=NVDA&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=AMZN&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=GOOGL&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=META&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=TSLA&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=JPM&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=JNJ&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=V&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=UNH&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=XOM&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=LLY&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=AVGO&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=PG&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=MA&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=HD&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=CVX&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=ABBV&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=MRK&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=COST&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=PEP&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=KO&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=WMT&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=BAC&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=CRM&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=AMD&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=NFLX&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=ADBE&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=ORCL&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=INTC&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=QCOM&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=IBM&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=GE&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=CAT&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=BA&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=GS&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=MS&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=BLK&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=SPGI&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=AXP&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=RTX&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=HON&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=LMT&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=UPS&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=DE&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=MMM&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=SYK&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=ISRG&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=TMO&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=ABT&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=BMY&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=AMGN&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=GILD&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=REGN&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=NOW&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=INTU&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=AMAT&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=LRCX&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=MU&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=TXN&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=PANW&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=CRWD&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=PLTR&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=COIN&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=UBER&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=ABNB&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=DASH&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=PYPL&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=SQ&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=V&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=WFC&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=C&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=USB&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=PNC&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=TFC&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=F&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=GM&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=NKE&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=SBUX&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=MCD&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=DIS&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=CMCSA&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=T&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=VZ&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=TMUS&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=CVS&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=WBA&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=CI&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=HUM&region=US&lang=en-US",
    "https://finance.yahoo.com/rss/2.0/headline?s=ELV&region=US&lang=en-US",

    # SEC EDGAR 8-K filings — broadest coverage of S&P 500 corporate events
    "https://www.sec.gov/cgi-bin/browse-edgar?action=getcurrent&type=8-K&dateb=&owner=include&count=40&output=atom",
]
